import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { Analytics } from "@vercel/analytics/next"
import Dropdown from "./components/dropdown";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="m-0 p-0">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-16 m-0 p-0`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
